[project]
name = "biped-tasks"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "biped-assets",
    "isaaclab[all,isaacsim]==2.1.0",
]

[tool.uv.sources]
biped-assets = { workspace = true }

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
