repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args:
    - --py37-plus
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.4
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
    - --select=I
  - id: ruff-format
- repo: https://github.com/nim65s/pre-commit-sort
  rev: v0.4.0
  hooks:
  - id: pre-commit-sort
- repo: https://github.com/pappasam/toml-sort
  rev: v0.24.2
  hooks:
  - id: toml-sort-fix
    exclude: uv.lock
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
