policy_name: "unitree"

mujoco:
  experiment_name: "h12_locomotion"

  render_dt: 0.02
  decimation: 20
  episode_length: 5

  enable_GUI: True
  fix_base: False
  real_time: False
  enable_keyboard: True
  log_data: False
  elastic_band: False

real:
  net_interface: eth0
  use_mujoco: True
