policy_path: "/home/cperrot/h1v2-Isaac/logs/rsl_rl/h12_flat/2025-06-04_16-19-27/exported/policy.pt"
xml_path: "/home/cperrot/h1v2-Isaac/urdfs/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [200, 200, 200, 300, 40, 40, 200, 200, 200, 300, 40, 40]
kds: [2.5, 2.5, 2.5, 4, 2, 2,  2.5, 2.5, 2.5, 4, 2, 2]

default_angles: [0, -0.16, 0.0, 0.36, -0.2, 0.0, 
                 0, -0.16, 0.0, 0.36, -0.2, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

cmd_init: [0.5, 0, 0]